#include "DreamFXGeneratedAssetGuard.h"

#include "DreamFXModule.h"
#include "Generation/DreamFXProvenance.h"
#include "Workspace/DreamFXWorkspaceService.h"

#include "Editor.h"
#include "Framework/Notifications/NotificationManager.h"
#include "HAL/PlatformProcess.h"
#include "Misc/Paths.h"
#include "NiagaraSystem.h"
#include "Subsystems/AssetEditorSubsystem.h"
#include "UObject/UObjectGlobals.h"
#include "Widgets/Notifications/SNotificationList.h"

#define LOCTEXT_NAMESPACE "DreamFXGeneratedAssetGuard"

namespace UE::DreamFX::Editor
{
	namespace
	{
		FDelegateHandle GAssetOpenedHandle;
		FDelegateHandle GObjectModifiedHandle;

		/**
		 * Assets already warned about this session.
		 *
		 * OnObjectModified fires on nearly every interaction with an open asset; warning each time
		 * would turn a useful signal into wallpaper someone learns to ignore.
		 */
		TSet<FString> GWarnedAssets;

		void ShowGeneratedNotice(const UObject* Asset, const FProvenanceStamp& Stamp, bool bModified)
		{
			const FString SourceName = Stamp.SourceRelativePath.IsEmpty()
				? FPaths::GetCleanFilename(Stamp.SourceFullPath)
				: Stamp.SourceRelativePath;

			FNotificationInfo Info(FText::Format(
				bModified
					? LOCTEXT("DreamFXModified", "'{0}' is generated from {1}. This edit will be overwritten by the next DreamFX build -- change the source file instead.")
					: LOCTEXT("DreamFXOpened", "'{0}' is generated from {1}. Hand edits are overwritten by the next DreamFX build."),
				FText::FromString(Asset->GetName()),
				FText::FromString(SourceName)));

			Info.ExpireDuration = bModified ? 8.0f : 6.0f;
			Info.bFireAndForget = true;
			Info.bUseSuccessFailIcons = false;

			// The source path is the actionable part of the message, so make it one click away.
			// Through the same launch chain the menus use (plan-v3 E5): the OS default handler for a
			// .dfs is whatever happens to be registered, which on most machines is nothing at all.
			if (!Stamp.SourceFullPath.IsEmpty())
			{
				const FString SourcePath = Stamp.SourceFullPath;
				Info.HyperlinkText = LOCTEXT("DreamFXOpenSource", "Open source file");
				Info.Hyperlink = FSimpleDelegate::CreateLambda([SourcePath]()
				{
					FDreamFXLaunchUtils::LaunchTextFileInPreferredEditor(SourcePath);
				});
			}

			FSlateNotificationManager::Get().AddNotification(Info);
		}

		void OnAssetOpened(UObject* Asset, IAssetEditorInstance* /*Editor*/)
		{
			if (Asset == nullptr)
			{
				return;
			}

			FProvenanceStamp Stamp;
			if (!FProvenance::Read(Asset, Stamp))
			{
				return;
			}

			ShowGeneratedNotice(Asset, Stamp, /*bModified=*/false);
			UE_LOG(LogDreamFX, Display, TEXT("'%s' was generated by DreamFX from '%s'."),
				*Asset->GetPathName(), *Stamp.SourceFullPath);
		}

		void OnObjectModified(UObject* Object)
		{
			// Only the generated asset itself matters. Its inner objects (emitters, scripts, renderers)
			// fire too, and warning on each of those would mean several toasts per keystroke.
			const UNiagaraSystem* System = Cast<UNiagaraSystem>(Object);
			if (System == nullptr)
			{
				return;
			}

			FProvenanceStamp Stamp;
			if (!FProvenance::Read(Object, Stamp))
			{
				return;
			}

			const FString Key = Object->GetPathName();
			if (GWarnedAssets.Contains(Key))
			{
				return;
			}
			GWarnedAssets.Add(Key);

			ShowGeneratedNotice(Object, Stamp, /*bModified=*/true);
		}
	}

	void FGeneratedAssetGuard::Register()
	{
		if (GEditor == nullptr)
		{
			return;
		}

		if (UAssetEditorSubsystem* Subsystem = GEditor->GetEditorSubsystem<UAssetEditorSubsystem>())
		{
			GAssetOpenedHandle = Subsystem->OnAssetOpenedInEditor().AddStatic(&OnAssetOpened);
		}

		GObjectModifiedHandle = FCoreUObjectDelegates::OnObjectModified.AddStatic(&OnObjectModified);
	}

	void FGeneratedAssetGuard::Unregister()
	{
		if (GEditor != nullptr)
		{
			if (UAssetEditorSubsystem* Subsystem = GEditor->GetEditorSubsystem<UAssetEditorSubsystem>())
			{
				Subsystem->OnAssetOpenedInEditor().Remove(GAssetOpenedHandle);
			}
		}

		FCoreUObjectDelegates::OnObjectModified.Remove(GObjectModifiedHandle);
		GWarnedAssets.Reset();
	}
}

#undef LOCTEXT_NAMESPACE
